name = "WmeFabric"
author = "WmeLuna"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9a6f2178ca22a1484599e10e0a9f8388bf6018e594d064133c1ec97fbaceda5"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
