name = "WmeFabric"
author = "WmeLuna"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e6135ab0ef1ec13491380dd8d495168305e1243d07078b3d8b41b8f716d1002"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
