name = "WmeFabric"
author = "WmeLuna"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a9d2f76b2868a9560bcf7a02255b38ee8bdb018132299bdb0614c9bbaf9e031"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
