name = "WmeFabric"
author = "WmeLuna"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35cae54d2bbc8d41e5780801aa42a672448d2fe09eb0b25f8ef7262a96f242bf"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
