name: Update
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: | 
          go install github.com/packwiz/packwiz@latest
          packwiz update --all
          packwiz refresh
          packwiz mr export
      - run: |
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git add .
          git commit -m "Update"
          git push