name: Update
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19
          
      # Cache Golang Dependancies
      - name: Determine Golang cache paths
        id: golang-path
        run: |
          echo "build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
          echo "module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
        shell: bash
      - name: Download Packwiz Cache
        run: wget -nv https://github.com/packwiz/packwiz/raw/main/go.sum
        
      - name: Setup Golang Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.golang-path.outputs.build }}
            ${{ steps.golang-path.outputs.module }}
          key: packwiz-golang-${{ hashFiles('**/go.sum') }}
            
      - name: Update Packwiz and mods
        run: | 
          go install github.com/packwiz/packwiz@latest
          packwiz update --all -y
          packwiz refresh
      - name: Commit
        run: |
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git add .
          git commit -m "Update" || exit 0
          git push || exit 0
