name: Update
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: | 
          go install github.com/packwiz/packwiz@latest
          packwiz update --all
          packwiz refresh
          packwiz mr export -o WmeFabric.mrpack
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: latest
          prerelease: true
          title: ModPack Release
          files: |
            ./WmeFabric.mrpack