name: Update
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Update Packwiz and mods
        run: | 
          go install github.com/packwiz/packwiz@latest
          packwiz update --all -y
          packwiz refresh
      - name: Commit
        run: |
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git add .
          git commit -m "Update" || exit 0
          git push || exit 0
